// generated: canonical JNI 1.6 slot indices (byte offset = index*8)
#define JNI_SLOT_COUNT 233
#define J_FindClass 6
#define J_GetMethodID 33
#define J_GetStaticMethodID 113
#define J_GetFieldID 94
#define J_GetStaticFieldID 144
#define J_GetStaticObjectField 145
#define J_GetStaticIntField 150
#define J_NewStringUTF 167
#define J_GetStringUTFChars 169
#define J_ReleaseStringUTFChars 170
#define J_GetStringUTFLength 168
#define J_NewString 163
#define J_GetStringChars 165
#define J_ReleaseStringChars 166
#define J_GetStringLength 164
#define J_GetByteArrayElements 184
#define J_GetByteArrayRegion 200
#define J_SetByteArrayRegion 208
#define J_ReleaseByteArrayElements 192
#define J_GetArrayLength 171
#define J_NewByteArray 176
#define J_NewIntArray 179
#define J_NewObjectArray 172
#define J_GetObjectArrayElement 173
#define J_SetObjectArrayElement 174
#define J_GetObjectClass 31
#define J_GetVersion 4
#define J_ExceptionOccurred 15
#define J_ExceptionClear 17
#define J_ExceptionCheck 228
#define J_ExceptionDescribe 16
#define J_DeleteLocalRef 23
#define J_NewGlobalRef 21
#define J_DeleteGlobalRef 22
#define J_NewLocalRef 25
#define J_NewWeakGlobalRef 226
#define J_DeleteWeakGlobalRef 227
#define J_IsSameObject 24
#define J_EnsureLocalCapacity 26
#define J_PushLocalFrame 19
#define J_PopLocalFrame 20
#define J_RegisterNatives 215
#define J_UnregisterNatives 216
#define J_GetJavaVM 219
#define J_MonitorEnter 217
#define J_MonitorExit 218
#define J_IsInstanceOf 32
#define J_AllocObject 27
#define J_CallObjectMethod 34
#define J_CallObjectMethodV 35
#define J_CallObjectMethodA 36
#define J_CallVoidMethod 61
#define J_CallVoidMethodV 62
#define J_CallVoidMethodA 63
#define J_CallIntMethod 49
#define J_CallIntMethodV 50
#define J_CallIntMethodA 51
#define J_CallBooleanMethod 37
#define J_CallBooleanMethodV 38
#define J_CallBooleanMethodA 39
#define J_CallStaticObjectMethod 114
#define J_CallStaticObjectMethodV 115
#define J_CallStaticObjectMethodA 116
#define J_CallStaticVoidMethod 141
#define J_CallStaticVoidMethodV 142
#define J_CallStaticVoidMethodA 143
#define J_CallStaticIntMethod 129
#define J_CallStaticIntMethodV 130
#define J_CallStaticIntMethodA 131
#define J_CallStaticBooleanMethod 117
#define J_CallStaticBooleanMethodV 118
#define J_CallStaticBooleanMethodA 119
#define J_GetPrimitiveArrayCritical 222
#define J_ReleasePrimitiveArrayCritical 223
#define J_CallLongMethod 52
#define J_CallLongMethodV 53
#define J_CallLongMethodA 54
#define J_CallFloatMethod 55
#define J_CallFloatMethodV 56
#define J_CallFloatMethodA 57
#define J_CallStaticLongMethod 132
#define J_CallStaticLongMethodV 133
#define J_CallStaticLongMethodA 134
#define J_CallStaticFloatMethod 135
#define J_CallStaticFloatMethodV 136
#define J_CallStaticFloatMethodA 137
#define J_GetIntArrayElements 187
#define J_ReleaseIntArrayElements 195
#define J_NewObject 28
#define J_NewObjectV 29
#define J_NewObjectA 30
#define J_NewDirectByteBuffer 229
#define J_GetDirectBufferAddress 230
#define J_GetDirectBufferCapacity 231
